version: "3"

services:

  routeros-7-2-3:
    image: evilfreelancer/docker-routeros:7.2.3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "180:80"
      - "500:500"
      - "4500:4500"
      - "1701:1701"
      - "1702:1702"
      - "1723:1723"
      - "12222:22"
      - "12223:23"
      - "18291:8291"
      - "18728:8728"
      - "18729:8729"

  routeros-7-2-3:
    image: evilfreelancer/docker-routeros:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "180:80"
      - "500:500"
      - "4500:4500"
      - "1701:1701"
      - "1702:1702"
      - "1723:1723"
      - "12222:22"
      - "12223:23"
      - "18291:8291"
      - "18728:8728"
      - "18729:8729"
